// <auto-generated />
namespace WebApiCarcel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class primeraMigracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primeraMigracion));
        
        string IMigrationMetadata.Id
        {
            get { return "201711052341150_primeraMigracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
